# Site settings
title: Cambridge Existential Risks Initiative
email: ceri-contact@srcf.net
url: https://camxrisk.org
description: "Cambridge Existential Risks Initiative (CERI) is a network of academics and students at the University of Cambridge and beyond, working to mitigate existential risks."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Facebook
    url: https://www.facebook.com/cambxrisk
    fa-icon: fa-facebook-f
  - title: Instagram
    url: https://www.instagram.com/cambxrisk/
    fa-icon: fa-instagram
  - title: LinkedIn
    url: https://www.linkedin.com/company/cambridge-existential-risks-initiative/
    fa-icon: fa-linkedin-square
  - title: YouTube
    url: https://www.youtube.com/channel/UCaGONW94o_nEN5zV7UwElzw
    fa-icon: fa-youtube-play

# Build settings
markdown: kramdown
permalink: pretty
